<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnRanking</name>
   <tag></tag>
   <elementGuidId>53c36e15-7014-4888-8768-6ead6bc2c1ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div[1]/div/ul/a[3]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div[1]/div/ul/a[3]/li</value>
      <webElementGuid>f86f99c8-7769-4e99-9ac5-7f4126600e69</webElementGuid>
   </webElementProperties>
</WebElementEntity>
