<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>viewDetailBtn</name>
   <tag></tag>
   <elementGuidId>d095facb-cc18-48e7-9235-f738e0168248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div[2]/div[1]/div/div/div[2]/div[1]/div[1]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div[2]/div[1]/div/div/div[2]/div[1]/div[1]/span[2]</value>
      <webElementGuid>b56f2dea-f82a-485d-8c89-d0fb0fe44a11</webElementGuid>
   </webElementProperties>
</WebElementEntity>
