<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>commentField</name>
   <tag></tag>
   <elementGuidId>8aa9d558-3ca1-448d-82ea-5c934f8a30e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mui-1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mui-1&quot;]</value>
      <webElementGuid>62f36e52-04e6-4026-97a4-29274bbeda42</webElementGuid>
   </webElementProperties>
</WebElementEntity>
