<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendIcon</name>
   <tag></tag>
   <elementGuidId>b3272588-b196-4e51-8798-3144704163d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[2]/div[1]/div[5]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[2]/div[1]/div[5]/button</value>
      <webElementGuid>ba62a955-1687-4617-89f6-00f380e12a38</webElementGuid>
   </webElementProperties>
</WebElementEntity>
