<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTrending</name>
   <tag></tag>
   <elementGuidId>1d311e83-56aa-45f9-8dde-aeedd5c190b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div[1]/a[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div[1]/a[2]/a</value>
      <webElementGuid>0cf2c30a-b4f0-4586-a41b-2aa268458a74</webElementGuid>
   </webElementProperties>
</WebElementEntity>
