<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown</name>
   <tag></tag>
   <elementGuidId>e9934a1c-8c48-43bb-9d96-190f8d2e7c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/nav/div/div/ul[2]/li/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/nav/div/div/ul[2]/li/div/a</value>
      <webElementGuid>e40504a4-a37c-44b7-83d7-13232829ded6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
