<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleThread</name>
   <tag></tag>
   <elementGuidId>0a9c0237-9501-40fd-bddf-e9ea492e8cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div/div[2]/form/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>99ce39e1-61b5-46ab-9cdc-84462c0c85d2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
