<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTeknologi</name>
   <tag></tag>
   <elementGuidId>ab79eeb4-2eb4-42c1-98b4-8b1c644a6be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div/div[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div[2]/div/div[1]/button[1]</value>
      <webElementGuid>38a3cc34-af25-40ed-b689-b195d5a66656</webElementGuid>
   </webElementProperties>
</WebElementEntity>
