<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnOK</name>
   <tag></tag>
   <elementGuidId>d46d00dd-2461-492d-a37a-9ad11bbed0cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[6]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[6]/button[1]</value>
      <webElementGuid>c9f13f69-84e8-43e9-92ff-f1df991fc0e2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
