<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passwordField</name>
   <tag></tag>
   <elementGuidId>187ca5b2-3ab6-4442-98dc-ae0787c1ba35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/div[2]/div/div/form/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/div[2]/div/div/form/div[2]/input</value>
      <webElementGuid>3e95eda5-044f-4135-9f4e-ae63c0837353</webElementGuid>
   </webElementProperties>
</WebElementEntity>
