<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnRegister</name>
   <tag></tag>
   <elementGuidId>db5a19cf-cf4b-4c29-8d50-7e82ee39b870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/div/div/div/div[2]/div/div/form/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/div/div/div/div[2]/div/div/form/button</value>
      <webElementGuid>d034d6d0-da6a-4806-aeef-0716a36e9dce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
