<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailField</name>
   <tag></tag>
   <elementGuidId>c1733c84-5a82-499a-9f7d-aa977555c50d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div/div/div/div/div[2]/div/div/form/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div/div/div/div/div[2]/div/div/form/div[2]/input</value>
      <webElementGuid>a3f488ae-50de-41b5-8f01-80cf72de72cf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
