<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>usernameField</name>
   <tag></tag>
   <elementGuidId>9073c570-c508-4c85-a26b-7fadbfaa3d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div/div/div/div/div/div[2]/div/div/form/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div/div/div/div/div/div[2]/div/div/form/div[1]/input</value>
      <webElementGuid>7b868c37-8c64-4803-9291-7fcff57dcf5f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
