<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEditProfile</name>
   <tag></tag>
   <elementGuidId>24fb9568-048d-4209-b48c-70111ac88a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/section/div/div[2]/div/div[1]/div[2]/div[2]/div/div[2]/a/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/section/div/div[2]/div/div[1]/div[2]/div[2]/div/div[2]/a/button</value>
      <webElementGuid>89828c0e-b70b-4225-ac15-eb06a17259c2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
