<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnProfile</name>
   <tag></tag>
   <elementGuidId>186023a3-d2ab-425c-aa63-512ee4d86825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[1]/div/ul/a[5]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[1]/div/ul/a[5]/li</value>
      <webElementGuid>4e3043b3-bd5d-4217-b551-05aef66765e3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
