<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dobField</name>
   <tag></tag>
   <elementGuidId>db9feb03-26ca-4dee-99b1-d8a6bdec9c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[2]/form/div[5]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[2]/form/div[5]/input</value>
      <webElementGuid>28dcfe49-989d-4493-83bf-e1e13d728a45</webElementGuid>
   </webElementProperties>
</WebElementEntity>
