<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>educationField</name>
   <tag></tag>
   <elementGuidId>63442c7f-da8a-4a9f-ad0f-d6e255fa0756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[2]/form/div[6]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[2]/form/div[6]/select</value>
      <webElementGuid>571361a8-d315-4ad6-bc32-438e2e65eb6b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
