<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailField</name>
   <tag></tag>
   <elementGuidId>9744fb8d-a0de-4522-9d22-b5fa7f30281f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[2]/form/div[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[2]/form/div[4]/input</value>
      <webElementGuid>e3575651-f160-4835-b191-fd6dea545f95</webElementGuid>
   </webElementProperties>
</WebElementEntity>
