<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaBelakangField</name>
   <tag></tag>
   <elementGuidId>bbb4c9d8-bcb7-484b-a40a-65d63cbb1260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[2]/form/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[2]/form/div[2]/input</value>
      <webElementGuid>bc0696f4-23ab-49b2-ae5e-d601058d6410</webElementGuid>
   </webElementProperties>
</WebElementEntity>
